name: Build and Test Ekatra

# This workflow runs on pushes or pull requests to the 'main' branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Build and Test on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # The kitware/cmake-action has been removed. We will use the version of
      # CMake pre-installed on the runner, which is usually modern enough.
      - name: Check CMake Version
        run: cmake --version

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      # Updated the ctest command to be more compatible.
      # --output-on-failure will print logs if a test fails.
      - name: Run Tests
        working-directory: ./build
        run: ctest --output-on-failure
