name: Build and Test Ekatra

# This workflow runs on pushes or pull requests to the 'main' branch
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        name: Build and Test on ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup CMake
              uses: kitware/cmake-action@v2
              with:
                  cmake-version: "3.24.0" # A version that supports --color-auto

            - name: Configure CMake
              run: cmake -S . -B build

            - name: Build
              run: cmake --build build

            - name: Run Tests
              working-directory: ./build
              run: ctest --color-auto --verbose
