name: Build and Test Ekatra

# This workflow runs on pushes or pull requests to the 'main' branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Build and Test on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        if: runner.os == 'Windows'
        run: choco install ninja

      - name: Check CMake Version
        run: cmake --version
.
      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: ./build
        run: ctest --output-on-failure
